import dayjs from "@/lib/dayjs"

// Master Patient Clinical Templates
const patientTemplates = [
  {
    prefix: "นาย",
    firstName: "สมชาย",
    lastName: "ใจดี",
    gender: "ชาย",
    age: 65,
    dob: "12 ม.ค. 2504",
    rights: "บัตรทอง (UC)",
    department: "OPD อายุรกรรม",
    doctor: "นพ. กิตติพงศ์ วงศ์สมุทร (ว.45892)",
    drg: "I70Z",
    diagnosis: "Major Hip Joint Replacement",
    adjrw: 2.2234,
    cost: 142350,
    risk: "สูง",
    alerts: 3,
    status: "รอตรวจสอบ",
    allergies: "Penicillin, Amoxicillin (ผื่นคัน, แน่นหน้าอก)",
    allergyDetails: [
      {
        drug: "Penicillin G / V",
        group: "Penicillins & Beta-lactams",
        reaction: "ผื่นคันทั่วตัว, แน่นหน้าอก, หลอดลมหดเกร็ง (Anaphylaxis)",
        severity: "Severe",
        date: "12 ม.ค. 2562",
        hospital: "รพ. ประจำจังหวัด",
      },
      {
        drug: "Amoxicillin + Clavulanate",
        group: "Aminopenicillins",
        reaction: "Angioedema บวมริมฝีปากและรอบตา",
        severity: "Severe",
        date: "08 พ.ค. 2564",
        hospital: "รพ. ชุมชน",
      },
    ],
    underlying: "DM Type 2, HT, Dyslipidemia",
    bloodGroup: "O+",
    phone: "081-234-5678",
    citizenId: "1-1002-00345-67-8",
    chiefComplaint: "ปวดสะโพกขวา เดินลงน้ำหนักไม่ได้ 2 วัน",
    presentIllness: "มีอาการปวดข้อสะโพกขวาเรื้อรังมา 2 สัปดาห์ ปวดมากขึ้นจนเดินไม่ไหว ไม่มีไข้",
    physicalExam: "Vitals stable, tenderness over right hip joint, ROM limited due to pain",
    vitals: {
      systolic: "135",
      diastolic: "85",
      bp: "135/85",
      pr: "78",
      respiratory: "18",
      bodyTemperature: "36.8",
      o2sat: "98",
      weight: "68",
      height: "168",
      painScore: "6",
      esi: "ESI 3",
      barthelIndex: "14",
      cvdRisk: "10-20%",
    },
  },
  {
    prefix: "น.ส.",
    firstName: "กุลธิดา",
    lastName: "ชูมายงสี",
    gender: "หญิง",
    age: 9,
    dob: "05 ส.ค. 2560",
    rights: "จ่ายตรงกรมบัญชีกลาง (CS)",
    department: "OPD กุมารเวชศาสตร์",
    doctor: "พญ. อัญชลี ศรีวิไล (ว.38910)",
    drg: "J45Z",
    diagnosis: "Acute Bronchial Asthma",
    adjrw: 0.6842,
    cost: 32400,
    risk: "ปานกลาง",
    alerts: 1,
    status: "กำลังตรวจสอบ",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "Asthma (หอบหืด)",
    bloodGroup: "B+",
    phone: "089-876-5432",
    citizenId: "3-5012-00874-91-2",
    chiefComplaint: "หอบเหนื่อย ไอ มีเสียงหวีด แน่นหน้าอก 1 วัน",
    presentIllness: "มีประวัติหอบหืด 1 วันก่อนมาเริ่มมีอาการไอ แน่นหน้าอก หายใจเสียงหวีด พ่นยาที่บ้านแล้วไม่ดีขึ้น",
    physicalExam: "Chest: Bilateral wheezing, no crepitation, dyspnea",
    vitals: {
      systolic: "105",
      diastolic: "65",
      bp: "105/65",
      pr: "110",
      respiratory: "28",
      bodyTemperature: "37.2",
      o2sat: "94",
      weight: "28",
      height: "130",
      painScore: "2",
      esi: "ESI 2",
      barthelIndex: "18",
      cvdRisk: "< 10%",
    },
  },
  {
    prefix: "นางสาว",
    firstName: "วิภาวดี",
    lastName: "รุ่งเรือง",
    gender: "หญิง",
    age: 72,
    dob: "20 พ.ย. 2497",
    rights: "ประกันสังคม (SSO)",
    department: "IPD หอผู้ป่วยอายุรกรรมหญิง 3",
    doctor: "นพ. กิตติพงศ์ วงศ์สมุทร (ว.45892)",
    drg: "I48Z",
    diagnosis: "Congestive Heart Failure",
    adjrw: 1.1321,
    cost: 68450,
    risk: "ปานกลาง",
    alerts: 2,
    status: "รอตรวจสอบ",
    allergies: "Sulfa, Aspirin, Tramadol (3 รายการ)",
    allergyDetails: [
      {
        drug: "Co-trimoxazole (Bactrim)",
        group: "Sulfonamides",
        reaction: "Stevens-Johnson Syndrome (SJS) มีแผลในปาก ผื่นลอก",
        severity: "Life-threatening",
        date: "04 ก.พ. 2560",
        hospital: "รพ. ศูนย์",
      },
      {
        drug: "Aspirin",
        group: "NSAIDs / Salicylates",
        reaction: "Urticaria ลมพิษ ตาบวม หอบเหนื่อย",
        severity: "Moderate",
        date: "19 ส.ค. 2563",
        hospital: "รพ. เอกชน",
      },
      {
        drug: "Tramadol",
        group: "Opioid Analgesics",
        reaction: "เวียนศีรษะรุนแรง คลื่นไส้อาเจียน เหงื่อแตก",
        severity: "Mild",
        date: "11 พ.ย. 2565",
        hospital: "รพ. ทั่วไป",
      },
    ],
    underlying: "Heart Failure, CKD Stage 3",
    bloodGroup: "A+",
    phone: "086-555-1234",
    citizenId: "1-4099-00213-44-1",
    chiefComplaint: "เหนื่อยง่าย นอนราบไม่ได้ ขาบวมทั้ง 2 ข้าง 3 วัน",
    presentIllness: "ผู้ป่วยมีโรคหัวใจเดิม 3 วันก่อนมีอาการเหนื่อยหอบมากขึ้น นอนราบไม่ได้ ต้องหนุนหมอน 3 ใบ เท้าและขาสองข้างบวม",
    physicalExam: "JVP engorged, Bilateral basal crepitations, Pitting edema 2+ both legs",
    vitals: {
      systolic: "155",
      diastolic: "92",
      bp: "155/92",
      pr: "92",
      respiratory: "22",
      bodyTemperature: "36.7",
      o2sat: "95",
      weight: "62",
      height: "155",
      painScore: "3",
      esi: "ESI 2",
      barthelIndex: "12",
      cvdRisk: "30-40%",
    },
  },
  {
    prefix: "นาย",
    firstName: "ประสิทธิ์",
    lastName: "พรหมมา",
    gender: "ชาย",
    age: 58,
    dob: "14 ก.พ. 2511",
    rights: "บัตรทอง (UC)",
    department: "OPD ศัลยกรรม",
    doctor: "นพ. ธีรภัทร เมธาวี (ว.51240)",
    drg: "K35Z",
    diagnosis: "Acute Appendectomy",
    adjrw: 0.7489,
    cost: 45210,
    risk: "ต่ำ",
    alerts: 0,
    status: "เสร็จสิ้น",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "GERD, Fatty Liver",
    bloodGroup: "AB+",
    phone: "083-999-8877",
    citizenId: "2-1004-00192-33-0",
    chiefComplaint: "ปวดท้องรอบสะดือย้ายไปชายโครงขวาล่าง 1 วัน มีคลื่นไส้",
    presentIllness: "1 วันก่อนมาเริ่มปวดจุกแน่นรอบสะดือ ต่อมาย้ายมาปวดเสียดที่ท้องน้อยด้านขวา มีไข้ต่ำๆ และคลื่นไส้",
    physicalExam: "Abdomen: RLQ tenderness, positive McBurney's point, Rebound tenderness positive",
    vitals: {
      systolic: "128",
      diastolic: "80",
      bp: "128/80",
      pr: "88",
      respiratory: "20",
      bodyTemperature: "38.1",
      o2sat: "99",
      weight: "72",
      height: "172",
      painScore: "7",
      esi: "ESI 3",
      barthelIndex: "18",
      cvdRisk: "< 10%",
    },
  },
  {
    prefix: "นาง",
    firstName: "บุญเรือน",
    lastName: "คำแสน",
    gender: "หญิง",
    age: 49,
    dob: "30 เม.ย. 2520",
    rights: "บัตรทอง (UC)",
    department: "IPD หอผู้ป่วยอายุรกรรม 2",
    doctor: "พญ. ณิชานันท์ เจริญพร (ว.48901)",
    drg: "J18Z",
    diagnosis: "Community-acquired Pneumonia",
    adjrw: 0.9245,
    cost: 36780,
    risk: "ปานกลาง",
    alerts: 1,
    status: "รอตรวจสอบ",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "Pneumonia, HT",
    bloodGroup: "O+",
    phone: "087-112-2334",
    citizenId: "1-5099-00384-72-9",
    chiefComplaint: "ไข้สูง ไอมีเสมหะสีเหลืองเขียว หนาวสั่น 3 วัน",
    presentIllness: "มีไข้สูง หนาวสั่น ไอมีเสมหะเหนียวสีเขียว เจ็บหน้าอกเวลาหายใจเข้าลึกๆ อ่อนเพลีย เบื่ออาหาร 3 วัน",
    physicalExam: "Lung: Crepitation right lower lung, Rhonchi both lungs",
    vitals: {
      systolic: "122",
      diastolic: "78",
      bp: "122/78",
      pr: "96",
      respiratory: "24",
      bodyTemperature: "38.8",
      o2sat: "93",
      weight: "55",
      height: "158",
      painScore: "4",
      esi: "ESI 2",
      barthelIndex: "16",
      cvdRisk: "< 10%",
    },
  },
  {
    prefix: "นาย",
    firstName: "เอกชัย",
    lastName: "มั่นคง",
    gender: "ชาย",
    age: 70,
    dob: "08 ต.ค. 2499",
    rights: "จ่ายตรงกรมบัญชีกลาง (CS)",
    department: "IPD CCU ชั้น 5",
    doctor: "นพ. ธีรภัทร เมธาวี (ว.51240)",
    drg: "I21Z",
    diagnosis: "Acute Myocardial Infarction (AMI)",
    adjrw: 1.6542,
    cost: 95640,
    risk: "สูง",
    alerts: 2,
    status: "กำลังตรวจสอบ",
    allergies: "NSAIDs (Ibuprofen, Diclofenac)",
    allergyDetails: [
      {
        drug: "Ibuprofen / Diclofenac",
        group: "NSAIDs",
        reaction: "หลอดลมหดเกร็ง หายใจไม่ออก แน่นหน้าอกเฉียบพลัน",
        severity: "Severe",
        date: "05 มิ.ย. 2561",
        hospital: "รพ. ศิริราช",
      },
    ],
    underlying: "CAD, HT, Dyslipidemia",
    bloodGroup: "B+",
    phone: "082-443-2211",
    citizenId: "3-1007-00921-15-4",
    chiefComplaint: "แน่นหน้าอกตรงกลาง ร้าวไปกรามซ้าย เหงื่อแตกใจสั่น 2 ชม.",
    presentIllness: "มีอาการเจ็บแน่นหน้าอกเหมือนมีอะไรมาทับ นานเกิน 30 นาที ร้าวไปกรามและไหล่ซ้าย มีเหงื่อแตกท่วมตัว หายใจไม่อิ่ม",
    physicalExam: "Pale, sweating, Heart: regular tachycardia, no murmur, Lung: clear",
    vitals: {
      systolic: "160",
      diastolic: "98",
      bp: "160/98",
      pr: "104",
      respiratory: "22",
      bodyTemperature: "36.9",
      o2sat: "96",
      weight: "75",
      height: "168",
      painScore: "8",
      esi: "ESI 1",
      barthelIndex: "15",
      cvdRisk: ">= 40%",
    },
  },
  {
    prefix: "นาง",
    firstName: "มาลี",
    lastName: "ศรีสุข",
    gender: "หญิง",
    age: 61,
    dob: "19 ก.ย. 2508",
    rights: "บัตรทอง (UC)",
    department: "OPD คลินิกเบาหวานและความดัน",
    doctor: "นพ. กิตติพงศ์ วงศ์สมุทร (ว.45892)",
    drg: "E11Z",
    diagnosis: "Type 2 Diabetes mellitus with complications",
    adjrw: 0.8123,
    cost: 28900,
    risk: "ต่ำ",
    alerts: 0,
    status: "เสร็จสิ้น",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "Diabetes Mellitus, HT",
    bloodGroup: "A+",
    phone: "084-778-9900",
    citizenId: "1-1015-00482-66-3",
    chiefComplaint: "คอแห้ง กระหายน้ำบ่อย ปัสสาวะบ่อย ชาปลายมือเท้า",
    presentIllness: "มาติดตามอาการเบาหวานและความดัน ดื่มน้ำบ่อย ปัสสาวะกลางคืน 3-4 ครั้ง ชาปลายเท้าทั้งสองข้าง",
    physicalExam: "Normal sensation reduced at both feet, Eye: normal, Heart & Lung: normal",
    vitals: {
      systolic: "142",
      diastolic: "88",
      bp: "142/88",
      pr: "76",
      respiratory: "18",
      bodyTemperature: "36.6",
      o2sat: "98",
      weight: "64",
      height: "152",
      painScore: "1",
      esi: "ESI 4",
      barthelIndex: "20",
      cvdRisk: "20-30%",
    },
  },
  {
    prefix: "นาย",
    firstName: "องอาจ",
    lastName: "มองทางไกล",
    gender: "ชาย",
    age: 54,
    dob: "25 ธ.ค. 2515",
    rights: "ประกันสังคม (SSO)",
    department: "OPD อายุรกรรมทั่วไป",
    doctor: "พญ. ปิยะดา เกษมสุข (ว.42199)",
    drg: "G40Z",
    diagnosis: "Epilepsy with Status Epilepticus",
    adjrw: 1.054,
    cost: 52400,
    risk: "ปานกลาง",
    alerts: 1,
    status: "กำลังตรวจสอบ",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "Seizure disorder, Fatigue",
    bloodGroup: "O+",
    phone: "085-332-1144",
    citizenId: "3-1020-00745-88-2",
    chiefComplaint: "ชักเกร็งกระตุกทั้งตัว หมดสติ 1 ครั้ง 1 ชั่วโมงก่อนมา",
    presentIllness: "ญาติพบผู้ป่วยล้มลง ชักเกร็งกระตุกทั้งตัว ตากลับ กัดลิ้น หมดสติประมาณ 3 นาที หลังฟื้นมีอาการสับสนและปวดศีรษะ",
    physicalExam: "Post-ictal state, confused, neurological exam: no focal deficit",
    vitals: {
      systolic: "138",
      diastolic: "86",
      bp: "138/86",
      pr: "94",
      respiratory: "20",
      bodyTemperature: "37.4",
      o2sat: "97",
      weight: "70",
      height: "170",
      painScore: "5",
      esi: "ESI 2",
      barthelIndex: "14",
      cvdRisk: "10-20%",
    },
  },
  {
    prefix: "นาง",
    firstName: "ดวงใจ",
    lastName: "สุขสวัสดิ์",
    gender: "หญิง",
    age: 68,
    dob: "15 พ.ค. 2501",
    rights: "จ่ายตรงกรมบัญชีกลาง (CS)",
    department: "IPD หอผู้ป่วยอายุรกรรม 1",
    doctor: "พญ. ณิชานันท์ เจริญพร (ว.48901)",
    drg: "N17Z",
    diagnosis: "Acute Kidney Injury on CKD",
    adjrw: 1.842,
    cost: 87300,
    risk: "สูง",
    alerts: 2,
    status: "รอตรวจสอบ",
    allergies: "Ciprofloxacin (ผื่นลมพิษ)",
    allergyDetails: [
      {
        drug: "Ciprofloxacin",
        group: "Fluoroquinolones",
        reaction: "ผื่นลมพิษ หน้าบวม",
        severity: "Moderate",
        date: "14 ต.ค. 2565",
        hospital: "รพ. ประจำจังหวัด",
      },
    ],
    underlying: "CKD Stage 4, HT",
    bloodGroup: "B+",
    phone: "086-778-3321",
    citizenId: "1-5011-00234-55-6",
    chiefComplaint: "ปัสสาวะออกน้อย บวมทั่วตัว อ่อนเพลีย คลื่นไส้ 4 วัน",
    presentIllness: "มีโรคไตเรื้อรัง 4 วันก่อนปัสสาวะออกลดลงชัดเจน ตัวบวม ตาบวม เบื่ออาหาร คลื่นไส้อาเจียน อ่อนเพลียมาก",
    physicalExam: "Pale conjunctivae, eyelid edema, pitting edema 2+ both legs, dry tongue",
    vitals: {
      systolic: "168",
      diastolic: "102",
      bp: "168/102",
      pr: "84",
      respiratory: "20",
      bodyTemperature: "36.8",
      o2sat: "96",
      weight: "58",
      height: "150",
      painScore: "3",
      esi: "ESI 2",
      barthelIndex: "13",
      cvdRisk: "30-40%",
    },
  },
  {
    prefix: "นาย",
    firstName: "ธนากร",
    lastName: "พัฒนากุล",
    gender: "ชาย",
    age: 63,
    dob: "03 ก.ค. 2506",
    rights: "บัตรทอง (UC)",
    department: "IPD หอผู้ป่วยอายุรกรรม 3",
    doctor: "นพ. กิตติพงศ์ วงศ์สมุทร (ว.45892)",
    drg: "I63Z",
    diagnosis: "Cerebral Infarction (Acute Ischemic Stroke)",
    adjrw: 2.156,
    cost: 118400,
    risk: "สูง",
    alerts: 3,
    status: "กำลังตรวจสอบ",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "HT, Dyslipidemia, Atrial Fibrillation",
    bloodGroup: "A+",
    phone: "089-112-9988",
    citizenId: "1-1008-00912-44-3",
    chiefComplaint: "ปากเบี้ยว แขนขาซ้ายอ่อนแรง พูดไม่ชัด 2 ชั่วโมงก่อนมา",
    presentIllness: "ขณะนั่งทำงาน จู่ๆ มีอาการมุมปากตกด้านซ้าย ยกแขนซ้ายไม่ขึ้น พูดลิ้นคับปาก ญาติรีบนำส่งห้องฉุกเฉิน Fast Track",
    physicalExam: "Facial palsy left UMN, Motor power left arm Gr.2, leg Gr.3, NIHSS: 8",
    vitals: {
      systolic: "175",
      diastolic: "105",
      bp: "175/105",
      pr: "88",
      respiratory: "18",
      bodyTemperature: "37.0",
      o2sat: "97",
      weight: "74",
      height: "169",
      painScore: "2",
      esi: "ESI 1",
      barthelIndex: "10",
      cvdRisk: ">= 40%",
    },
  },
  {
    prefix: "นาง",
    firstName: "รัตนา",
    lastName: "เจริญสุข",
    gender: "หญิง",
    age: 56,
    dob: "22 ต.ค. 2513",
    rights: "ประกันสังคม (SSO)",
    department: "IPD หอผู้ป่วยศัลยกรรมหญิง",
    doctor: "นพ. ธีรภัทร เมธาวี (ว.51240)",
    drg: "K80Z",
    diagnosis: "Calculus of Gallbladder with Cholecystitis",
    adjrw: 1.342,
    cost: 74200,
    risk: "ปานกลาง",
    alerts: 1,
    status: "เสร็จสิ้น",
    allergies: "ไม่มีประวัติแพ้ยา",
    allergyDetails: [],
    underlying: "Gallstones, Dyslipidemia",
    bloodGroup: "O+",
    phone: "087-445-6677",
    citizenId: "3-4001-00567-89-0",
    chiefComplaint: "ปวดจุกแน่นท้องใต้ลิ้นปี่และชายโครงขวา ไข้ ตาเหลือง 2 วัน",
    presentIllness: "ปวดจุกเสียดท้องใต้ชายโครงขวา ร้าวไปสะบักขวา หลังทานอาหารมัน มีไข้หนาวสั่น คลื่นไส้ ปัสสาวะสีเข้ม 2 วัน",
    physicalExam: "Mild jaundice, Abdomen: tenderness at RUQ, Murphy's sign positive",
    vitals: {
      systolic: "132",
      diastolic: "82",
      bp: "132/82",
      pr: "90",
      respiratory: "20",
      bodyTemperature: "38.3",
      o2sat: "98",
      weight: "66",
      height: "156",
      painScore: "6",
      esi: "ESI 3",
      barthelIndex: "18",
      cvdRisk: "< 10%",
    },
  },
  {
    prefix: "นาย",
    firstName: "สมพร",
    lastName: "รักสงบ",
    gender: "ชาย",
    age: 71,
    dob: "11 มี.ค. 2498",
    rights: "บัตรทอง (UC)",
    department: "IPD ICU อายุรกรรม",
    doctor: "พญ. ณิชานันท์ เจริญพร (ว.48901)",
    drg: "A41Z",
    diagnosis: "Severe Sepsis with Septic Shock",
    adjrw: 2.784,
    cost: 185600,
    risk: "สูง",
    alerts: 3,
    status: "รอตรวจสอบ",
    allergies: "Cephalosporins (หายใจขัด แน่นหน้าอก)",
    allergyDetails: [
      {
        drug: "Ceftriaxone",
        group: "Cephalosporins",
        reaction: "หลอดลมหดเกร็ง หายใจขัด แน่นหน้าอก",
        severity: "Severe",
        date: "20 ส.ค. 2563",
        hospital: "รพ. ศูนย์",
      },
    ],
    underlying: "COPD, DM Type 2, BPH",
    bloodGroup: "AB+",
    phone: "081-998-3344",
    citizenId: "1-1005-00432-11-2",
    chiefComplaint: "ไข้สูง ซึม สับสน หายใจหอบเหนื่อย ความดันตก 1 วัน",
    presentIllness: "ญาติพบผู้ป่วยมีไข้สูง ซึมลง ไม่ค่อยตอบสนอง หายใจหอบเร็ว ปัสสาวะไม่ออก 1 วันก่อนมา",
    physicalExam: "Stuporous, Tachypnea, Cold clammy extremities, CRT > 3 sec",
    vitals: {
      systolic: "88",
      diastolic: "52",
      bp: "88/52",
      pr: "118",
      respiratory: "28",
      bodyTemperature: "39.2",
      o2sat: "91",
      weight: "60",
      height: "162",
      painScore: "0",
      esi: "ESI 1",
      barthelIndex: "5",
      cvdRisk: ">= 40%",
    },
  },
]

// Generate rich daily patient records spanning the last 30 days including today
export function generateDailyMockPatients() {
  const result = []
  let globalIndex = 1

  // Days: 0 (today), 1 (yesterday), 2, 3, ... 30 days back
  for (let daysAgo = 0; daysAgo <= 30; daysAgo++) {
    const targetDate = dayjs().subtract(daysAgo, "day")
    const dateStr = targetDate.format("YYYY-MM-DD")
    const dateYmdShort = targetDate.format("YYMMDD")
    const thaiDate = targetDate.format("D MMM BBBB")
    const isToday = daysAgo === 0
    const isYesterday = daysAgo === 1

    // 4 to 6 patients per day
    const countPerDay = (daysAgo % 3 === 0) ? 5 : (daysAgo % 2 === 0 ? 4 : 6)

    for (let i = 0; i < countPerDay; i++) {
      const templateIndex = (daysAgo * 3 + i) % patientTemplates.length
      const tpl = patientTemplates[templateIndex]

      const padIndex = String(globalIndex).padStart(4, "0")
      const patientId = `P${padIndex}`
      const hn = `67${String(10000 + (globalIndex % 90000)).padStart(6, "0")}`
      const an = `${dateYmdShort}-${String(100 + i).padStart(5, "0")}`

      const los = 2 + (i % 5)
      const startDate = targetDate.subtract(los, "day").format("D MMM BBBB")
      const dateRange = `${startDate} - ${thaiDate} (${los} วัน)`

      const fullName = `${tpl.prefix}${tpl.firstName} ${tpl.lastName}`

      // Vary status slightly based on days ago
      let status = tpl.status
      if (daysAgo === 0) {
        status = i % 2 === 0 ? "รอตรวจสอบ" : "กำลังตรวจสอบ"
      } else if (daysAgo > 10) {
        status = i % 3 === 0 ? "กำลังตรวจสอบ" : "เสร็จสิ้น"
      }

      result.push({
        id: patientId,
        an,
        hn,
        citizenId: tpl.citizenId,
        prefix: tpl.prefix,
        firstName: tpl.firstName,
        lastName: tpl.lastName,
        fullName,
        patient: fullName,
        gender: tpl.gender,
        age: tpl.age,
        dob: tpl.dob,
        demographics: `${tpl.gender}, ${tpl.age} ปี`,
        date: dateStr,
        dateRange,
        rights: tpl.rights,
        department: tpl.department,
        doctor: tpl.doctor,
        drg: tpl.drg,
        diagnosis: tpl.diagnosis,
        adjrw: Number((tpl.adjrw + (i * 0.05)).toFixed(4)),
        cost: tpl.cost + (i * 1250),
        risk: tpl.risk,
        alerts: tpl.alerts,
        status,
        allergies: tpl.allergies,
        allergyDetails: tpl.allergyDetails,
        underlying: tpl.underlying,
        bloodGroup: tpl.bloodGroup,
        phone: tpl.phone,
        chiefComplaint: tpl.chiefComplaint,
        presentIllness: tpl.presentIllness,
        physicalExam: tpl.physicalExam,
        vitals: tpl.vitals,
        isToday,
        isYesterday,
        daysAgo,
      })

      globalIndex++
    }
  }

  return result
}

// Generate the primary dataset
export const drgWorklistData = generateDailyMockPatients()
export const mockPatients = drgWorklistData
